apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  ## relicaset lables
  labels:
    purpose: dp-service
    project: roboshop
spec:
  replicas: 4
  selector:
  ## these lables are used to select the pods
    matchLabels:
      purpose: dp-service
      project: roboshop
  ## pod definition
  template:
    metadata:
      labels:
        purpose: dp-service
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:trixie-perl